name: Continous Integration

on: 
    pull_request:
        branches: [main]
    push:
        branches: [main]


jobs:
    testing_api:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo code into the runner
              uses: actions/checkout@v2 

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: Run the Unit/Integration
              run: npm test

      


